[package]
name = "feathermail"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.7.0"
actix-web = "4.9.0"
bincode = "1.3.3"
env_logger = "0.11.5"
log = "0.4.22"
minismtp = "0.1.0"
rustls = {version="0.23.12",features=["ring"]}
serde = "1.0.210"
sled = "0.34.7"
thiserror = "1.0.63"
